version: '3'
services:
  web:
    image: mcr.microsoft.com/vscode/devcontainers/dotnet:5.0
    volumes:
      # Mount the root folder that contains .git
      - /Users/onurgumus/.aspnet/https:/home/vscode/.aspnet/https
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    links:
      - auth
    # ...

  auth:
    image: mcr.microsoft.com/vscode/devcontainers/dotnet:5.0
    volumes:
      # Mount the root folder that contains .git
      - /Users/onurgumus/.aspnet/https:/home/vscode/.aspnet/https
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    # ...